version: "3.8"

services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/thunderbird
      - THUNDERBIRD_DEBUG=true
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: npm run dev

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: thunderbird
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
